from camel.agents import ChatAgent
from camel.configs import ChatGPTConfig
from camel.models import ModelFactory
from camel.toolkits import BrowserToolkit, PPTXToolkit
from camel.types import ModelPlatformType, ModelType
import json
import re


def main():
    # Create the base model for the agent
    model = ModelFactory.create(
        model_platform=ModelPlatformType.OPENAI,
        model_type=ModelType.GPT_4O_MINI,
        model_config_dict=ChatGPTConfig(temperature=0.0).as_dict(),
    )

    # Create web agent and planning agent models for BrowserToolkit
    web_agent_model = ModelFactory.create(
        model_platform=ModelPlatformType.OPENAI,
        model_type=ModelType.GPT_4O_MINI,
        model_config_dict=ChatGPTConfig(temperature=0.0).as_dict(),
    )

    planning_agent_model = ModelFactory.create(
        model_platform=ModelPlatformType.OPENAI,
        model_type=ModelType.GPT_4O_MINI,
        model_config_dict=ChatGPTConfig(temperature=0.0).as_dict(),
    )

    # Initialize BrowserToolkit
    browser_toolkit = BrowserToolkit(
        headless=True,
        web_agent_model=web_agent_model,
        planning_agent_model=planning_agent_model,
        channel="chromium",
    )

    # Initialize PPTXToolkit
    pptx_toolkit = PPTXToolkit(
        working_directory="./pptx_outputs"
    )

    # Create the ChatAgent with both BrowserToolkit and PPTXToolkit tools
    agent = ChatAgent(
        system_message="You are a helpful assistant that can browse the web and create PowerPoint presentations. When generating slides, produce JSON content suitable for the create_presentation tool.",
        model=model,
        tools=[*browser_toolkit.get_tools(), *pptx_toolkit.get_tools()],
    )

    # Since browser tool failed due to environment, fallback to known info
    camel_ai_info = '''\
CAMEL-AI (Collaborative Agents for Multi-Agent Learning) is a multi-agent AI framework designed to facilitate the development and deployment of collaborative AI agents.

Key features:
- Multi-agent system enabling collaboration and communication
- Scalability and flexibility for various agent types
- Incorporates machine learning for agent improvement
- Applications in autonomous vehicles, smart cities, resource management, and more
'''

    # Step 1: Generate slides JSON content based on the known info
    slide_generation_prompt = f"""
Create a PowerPoint presentation about "CAMEL-AI" based on the content below:
{camel_ai_info}

Requirements:
1. First slide must be a title slide with appropriate title and subtitle
2. Include bullet points summarizing key features and applications
3. Include at least one step-by-step slide
4. Include at least one table slide with relevant data
5. Use Markdown formatting (**bold**, *italic*) in bullet points
6. Add img_keywords for relevant images

Respond ONLY with the JSON content for the slides, suitable for the create_presentation tool.
"""

    print("=== Generating PowerPoint slides about CAMEL-AI ===")
    slide_response = agent.step(slide_generation_prompt)
    slide_json_str = slide_response.msgs[0].content
    print("Slide JSON content generated by agent:")
    print(slide_json_str)

    # Strip markdown code block if present
    slide_json_str = re.sub(r'^```json\n', '', slide_json_str)
    slide_json_str = re.sub(r'\n```$', '', slide_json_str)

    # Parse JSON content
    try:
        slide_json = json.loads(slide_json_str)
    except json.JSONDecodeError as e:
        print(f"Failed to parse slide JSON content: {e}")
        return

    # Step 2: Call the create_presentation tool directly with the JSON content
    create_presentation_tool = None
    for tool in agent.tool_dict.values():
        if tool.get_function_name() == "create_presentation":
            create_presentation_tool = tool
            break

    if create_presentation_tool is None:
        print("create_presentation tool not found in agent tools.")
        return

    # Convert slide_json list back to JSON string for the tool
    slide_json_content = json.dumps(slide_json)

    # Call the tool
    result = create_presentation_tool(slide_json_content, filename="camel_ai_presentation.pptx")
    print(f"PPTX creation result: {result}")


if __name__ == "__main__":
    main()
