#!/bin/bash
# Run a single evolve task (task_2) to test the evolve pipeline
# Uses the evolve_task_list.json generated by run_evolve.sh --dry-run

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CAMEL_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

EVOLVE_TASK_LIST="${CAMEL_ROOT}/code-agent/evolve_task_list.json"
CAMEL_MD="${SCRIPT_DIR}/CAMEL.md"
MODEL="openai/gpt-4.1-mini"
EXP_ID="evolve-fix"

# Extract only task_2 into a temp file
SINGLE_TASK_FILE="${CAMEL_ROOT}/code-agent/evolve_task_2.json"
python3 -c "
import json
with open('${EVOLVE_TASK_LIST}') as f:
    tasks = json.load(f)
single = {'task_2': tasks['task_2']}
with open('${SINGLE_TASK_FILE}', 'w') as f:
    json.dump(single, f, indent=4, ensure_ascii=False)
print('[INFO] Extracted task_2 to ${SINGLE_TASK_FILE}')
"

echo "=============================================="
echo "Evolve Single Task - task_2"
echo "=============================================="

cd "$SCRIPT_DIR"
python generic_code_agent.py \
    --context "$CAMEL_MD" \
    --tasks "$SINGLE_TASK_FILE" \
    --exp-id "$EXP_ID" \
    --model "$MODEL" \
    --max-tasks 1

# Move output
if [ -d "${CAMEL_ROOT}/task-script" ]; then
    TARGET_DIR="${CAMEL_ROOT}/task-script-${EXP_ID}"
    mkdir -p "$TARGET_DIR"
    cp -r "${CAMEL_ROOT}/task-script/"* "$TARGET_DIR/" 2>/dev/null || true
    rm -rf "${CAMEL_ROOT}/task-script"
    echo "[INFO] Scripts saved to: $TARGET_DIR"
fi

echo ""
echo "Done!"
